#!/usr/bin/env python

import glob
import os
import sys


def thumbnail(pathToFiles, size):
    command = "detox -r " + pathToFiles
    os.system(command)

    command = "find " + pathToFiles + " -type f -name '*.thumb.jpg' -delete"
    os.system(command)

    files = glob.glob(pathToFiles + '/**/*.jpg', recursive=True)
    for file in files:
        if os.path.isfile(file):
            command = "convert " + file + " -resize " + size + "x" + size + "^ " + file + ".thumb.jpg"
            os.system(command)

    files = glob.glob(pathToFiles + '/**/*.JPG', recursive=True)
    for file in files:
        if os.path.isfile(file):
            command = "convert " + file + " -resize " + size + "x" + size + "^ " + file + ".thumb.jpg"
            os.system(command)


if __name__ == '__main__':
    path = sys.argv[1]
    size = sys.argv[2]
    thumbnail(path, size)
